language: java
before_install: cd sonarQuest-backend
addons:
  #sonarcloud analysis with the travis plugin, see https://docs.travis-ci.com/user/sonarcloud/
  sonarcloud:
    organization: "viadee"
    #token is provided by the environment variable SONAR_TOKEN in travis settings
    token:  $SONAR_TOKEN
# the following command line builds the project, runs the tests with coverage and then executes the SonarCloud analysis.
# In case of external pull requests, no SONAR_SCANNER_HOME is defined, and SonarCloud analysis is not possible.
# (https://community.sonarsource.com/t/travis-plugin-is-failing-on-external-pull-request/807/3)
script: >-
  if [ "${SONAR_TOKEN}" != "" ]; then
    mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar
  else
    mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify
  fi
