version: '3'
services:
  backend:
    image: ghcr.io/viadee/sonarquest-backend:latest
    command: -DsimulateSonarServer=false
    ports:
     - "8080:8080"
  frontend:
    image: ghcr.io/viadee/sonarquest-frontend:latest
    ports:
      - "4200:80"
